# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'VenPro' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

# Pods for VenPro
# add the Firebase pod for Google Analytics
pod 'Firebase/Analytics'
pod 'FirebaseUI'
# add pods for any other desired Firebase products
# https://firebase.google.com/docs/ios/setup#available-pods

# add pods for dropdown menu
pod 'SideMenu'

end
